# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Stripe.xcworkspace", scheme: "LocalizationTester")
  end

  lane :preflight do
    sh("./ci_scripts/check_version.rb")
    sh("./ci_scripts/check_public_headers.rb")
    sh("./ci_scripts/check_category_linking.rb")
    sh("./ci_scripts/check_resource_bundle.rb")
    sh("./ci_scripts/check_for_new_localized_strings.sh")
  end

  lane :lint do
    sh("./ci_scripts/check_fauxpas.sh")
  end

  lane :ui_tests do
    sh("./ci_scripts/run_ui_tests.sh")
  end

  lane :legacy_tests_10 do
    sh("./ci_scripts/run_legacy_tests.sh \"platform=iOS Simulator,name=iPhone 6,OS=10.3.1\"'")
  end

  lane :legacy_tests_11 do
    sh("./ci_scripts/run_legacy_tests.sh \"platform=iOS Simulator,name=iPhone 6,OS=11.4"\"'")
  end

  lane :legacy_tests_12 do
    sh("./ci_scripts/run_legacy_tests.sh \"platform=iOS Simulator,name=iPhone 6,OS=12.4"\"'")
  end

  lane :analyze do
    sh("./ci_scripts/run_analyzer.sh")
  end

  lane :builds do
    sh("./ci_scripts/run_builds.sh")
  end

  lane :install_cocoapods_without_frameworks_objc do
    sh("./Tests/installation_tests/cocoapods/without_frameworks_objc/test.sh")
  end

  lane :installation_cocoapods_frameworks_objc do
    sh("./Tests/installation_tests/cocoapods/with_frameworks_objc/test.sh")
  end

  lane :installation_cocoapods_frameworks_swift do
    sh("./Tests/installation_tests/cocoapods/with_frameworks_swift/test.sh")
  end
  
  lane :install_carthage do
    sh("./Tests/installation_tests/carthage/test.sh")
  end

  lane :check_docs do
    sh("./ci_scripts/check_documentation.sh")
  end

  lane :tests do
    run_tests(scheme: "StripeiOS",
      devices: ["iPhone 7"])
  end
  
end
